version: '3.9'

services:
  backend:
    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: 'http://host.docker.internal:18545'
      ETHEREUM_JSONRPC_WS_URL: 'ws://host.docker.internal:18545'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER: 'true'
      ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: 'true'
      INDEXER_DISABLE_WITHDRAWALS_FETCHER: 'true'
      ETHEREUM_JSONRPC_CASE: EthereumJSONRPC.Case.Geth.HTTPWebSocket
      ETHEREUM_JSONRPC_WEB_SOCKET_CASE: EthereumJSONRPC.WebSocket.Case.Geth
